services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000" # Expose backend on localhost:5000
    environment:
      - NODE_ENV=production
      - API_PORT=5000

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Expose frontend on localhost:3000
    environment:
      - API_URL=http://localhost:5000/api
    depends_on:
      - backend
